remote_theme: pmarsceill/just-the-docs

title: OOP
description: თბილისის თავისუფალი უნივერსიტეტი, 2020/2021 გაზაფხული

baseurl: /
url: "https://freeuni-lekva.github.io/"

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock

heading_anchors: true

aux_links:
  "GitHub":
    - "//github.com/Freeuni-Lekva/oop-2021"
  "Google classroom":
    - "//classroom.google.com/c/MzA4OTM4NDQ0OTIx"

aux_links_new_tab: true

nav_sort: case_insensitive

search_enabled: false
